version: "3.8"
services:
  mysql:
    image: mysql:5.7
    command: "--default-authentication-plugin=mysql_native_password"
    restart: always
    volumes:
      - "./infra/mysql:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=prt_laravel
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
      - PMA_PORT=3306
    links:
      - mysql
    restart: always
    ports:
      - "4040:80"
    volumes:
      - "./infra/phpmyadmin/sessions:/sessions"
  nginx:
    build:
      context: ./infra/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:80"
    links:
      - "php"
    volumes:
      - ./src:/var/www

  php:
    build:
      context: ./infra/php
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./src:/var/www
      - ./infra/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    links:
      - "mysql"

  composer:
    image: composer
    command: "composer install"
    volumes:
      - ./src:/app
